version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: myuser
      MINIO_ROOT_PASSWORD: mypassword
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
  adminer:
    image: adminer
    ports:
      - "8080:8080"